language: go
env:
- GIMME_OS=linux GIMME_ARCH=amd64
- GIMME_OS=darwin GIMME_ARCH=amd64
- GIMME_OS=windows GIMME_ARCH=amd64
secure: "PU/1+y6e0NTk1BvieC09ruXygFJ/l4Jum1I75vV8XES7TPi2U03TAJJhXZcGzoy516V3z9/kfDXJUUzf5EC9jpp6uEwNRknkodhpllcdhv9UGDRjKETvoUSeWbQJnbA7xJHIVDEHlwbKZgJN/GVckjXuGk1BZU02fVXII1DweTVRJJwdAE//hRqlHE7EH607iuzvUqIUl3sQPgfQxVG+yxe6DRNBeV8Dwv7OWagJn/viqRanDtISeO+sc+kUbDKJJcfDSwQlVsjI9QLG3CiCjYaibniJz9ezrUa0gok187yaL1vCozDXkrmmKUrD7G03lz+sxGWWUpBs3Klt/zOiIcHlnBvFuB7NBHRMnURqZNFPOuSN8eJ3B2OGGqvmnfGEbHMrZAkSUjqmWQa7rBTPsij1VGzbzLlgfy+qh/e1aQ5NYw3JW5OJUNtlNd3GQQNRDcS2jphYuvh7CWFPhhajqbEsDZlRHZwU5c1egKlyaFBPFx0lc5cmRn22GZoWHOd+F3TWwey2uJHEbs51yApqy0/olOZS1JrC/s3rpliiz3CuaHmqySWdF1sNEoSeUnYddMmpY6KCo7YnpoRT/LHCI3TIAwiK9TMuOfaj/vmeswAlfyQ84LoiUeiwRk9oA0tOpUfr/4ZlLnWXEjnzlGRIOGKT/hLZH+v3O9FG5SrJxnw="
install:
- go get -d -v ./...
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls
- if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
- go test -v -covermode=count -coverprofile=coverage.out
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
